#
# Configuration File
#

# Information for compile
exclude:
  - "Gemfile"
  - "CNAME"
  - "LICENSE"
  - "*.md"
  - "*.js"
  - "*.json"
  - "images/favicon/*.md"
  - "images/favicon/*.html"
  - "images/favicon/*.xml"

# Plugins
plugins:
  - jekyll-sitemap

# Sass configuration
sass:
  sass_dir: _scss
#  sourcemap: never

# Collections
collections_dir: _collections
collections:
  related_sites:
    sort_by: order
  team_owners:
    sort_by: order
    member_type: owner
  team_others:
    sort_by: order
    member_type: other

# Information for deploy
baseurl: ""

# the base hostname & protocol for your site
url: https://cocoacolorlab.salon

##
## HEADER INFORMATION
##

# This is the site title
title: Cocoa Color Lab Salon
# This is the site description - must be between 25 and 160 characters for Bing SEO
description: >
  Upscale hair salon that strives to be the best in Brevard County.
  Masters of color, highlights, blonding, balayage, ombre, and keratin straightening.

# Website language
lang: en-US
# Header Title
header-title: Cocoa Color Lab Salon
# Header Tagline
header-tagline1: The beauty of hair
header-tagline2: The science of perfection

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: hello@cocoacolorlab.salon

##
## Global Social Links
##
facebook: https://www.facebook.com/CocoaColorLab.salon/
instagram: https://www.instagram.com/CocoaColorLab.salon/
tiktok: https://www.tiktok.com/@CocoaColorLab.salon
youtube: https://www.youtube.com/@CocoaColorLabSalon

##
## Global Images
##
facebook-image: /images/icons/facebook.svg
instagram-image: /images/icons/instagram.svg
tiktok-image: /images/icons/tiktok.svg
youtube-image: /images/icons/youtube.svg
linkedin-image: /images/icons/linkedin.svg
email-image: /images/icons/email.svg

##
## Footer
##
footer-description: Find us on social media.
footer-copyright-text: Cocoa Color Lab, LLC
footer-copyright-year: 2023
