#
# Configuration File
#

# Information for compile
exclude: ["Gemfile", "CNAME", "LICENSE", "README.md", "AUTHORING.md"]

# Sass configuration
sass:
  sass_dir: _scss

# Collections
collections_dir: _collections
collections:
  team_owners:
    sort_by: order
    member_type: owner
  team_others:
    sort_by: order
    member_type: other

# Information for deploy
baseurl: ""

# the base hostname & protocol for your site
url: "https://cocoacolorlab.salon"

##
## HEADER INFORMATION
##

# This is the site title
title: Cocoa Color Lab Salon
# This is the site description - must be between 25 and 160 characters for Bing SEO
description: >
  Upscale hair salon that strives to be the best in Brevard County.
  Masters of color, highlights, blonding, balayage, ombre, and keratin straightening.

# Website language
lang: en-US
# Header Title
header-title: Cocoa Color Lab Salon
# Header Tagline
header-tagline1: The beauty of hair
header-tagline2: The science of perfection

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: hello@cocoacolorlab.salon

##
## Global Social Links
##
facebook: "https://www.facebook.com/CocoaColorLab.salon/"
instagram: "https://www.instagram.com/CocoaColorLab.salon/"
tiktok: "https://www.tiktok.com/@CocoaColorLab.salon"
youtube: "https://www.youtube.com/@CocoaColorLabSalon"

##
## Global Images
##
facebook-image: "/images/icons/facebook.svg"
instagram-image: "/images/icons/instagram.svg"
tiktok-image: "/images/icons/tiktok.svg"
youtube-image: "/images/icons/youtube.svg"
linkedin-image: "/images/icons/linkedin.svg"
email-image: "/images/icons/email.svg"

##
## Related
##
related-title: Related Sites

related:
  # Salon
  - title: <span title="CocoaColorLab.Salon"><b>C</b>ocoa<b>C</b>olor<b>L</b>ab.<b>S</b>alon</span>
    categories: [Lisa]
    image: colorlab-salon-related-image.svg
    info: Lisa's hair salon services (this site)
    url: "https://cocoacolorlab.salon"
  # Com
  - title: <span title="CocoaColorLab.Art"><b>C</b>ocoa<b>C</b>olor<b>L</b>ab.<b>C</b>om</span>
    categories: [Lisa,Ray]
    image: colorlab-com-related-image.svg
    info: Main company website
    url: "https://cocoacolorlab.com"
  # Ink
  - title: <span title="CocoaColorLab.Ink"><b>C</b>ocoa<b>C</b>olor<b>L</b>ab.<b>I</b>nk</span>
    categories: [Ray]
    image: colorlab-ink-related-image.svg
    info: Ray's tattoo services
    url: "https://cocoacolorlab.ink"
  # Art
  - title: <span title="CocoaColorLab.Art"><b>C</b>ocoa<b>C</b>olor<b>L</b>ab.<b>A</b>rt</span>
    categories: [Ray]
    image: colorlab-art-related-image.svg
    info: Ray's art portfolio
    url: "https://cocoacolorlab.art"

##
## Footer
##
footer-description: Find us on social media.
footer-copyright-text: Cocoa Color Lab, LLC
footer-copyright-year: 2023
