#
# Sera - OnePage Jekyll Theme
# Configuration File
#

# Information for compile
exclude: ["Gemfile", "CNAME", "LICENSE", "README.md", "AUTHORING.md"]

# Sass configuration
sass:
  sass_dir: _scss

# Information for deploy
baseurl: ""

# the base hostname & protocol for your site
url: "https://cocoacolorlab.salon"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

#######################################################
#######################################################
###############   HEADER INFORMATION   ###############
#######################################################
#######################################################

# This is your site title
title: Cocoa Color Lab Salon
# Website language
lang: en-US
# Header Title
header-title: Cocoa Color Lab Salon
# Header Tagline
header-tagline: Cocoa Color Lab Salon

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: hello@cocoacolorlab.salon

####################################
######  Global Social Links   ######
####################################
facebook: "https://www.facebook.com/CocoaColorLab.salon/"
instagram: "https://www.instagram.com/CocoaColorLab.salon/"
tiktok: "https://www.tiktok.com/@CocoaColorLab.salon"
youtube: "https://www.youtube.com/@CocoaColorLab.salon"

#########################
######   Widgets   ######
#########################

#####################################
#############   About   #############
#####################################
about-title: About Us
about-description-short: Cocoa Color Lab Salon by Lisa Cardillo.
about-description-long: >
  Lisa is a master hair stylist and colorist who is licensed in New York, Maryland, and Florida.
  More coming soon.

#####################################
############  Portfolio  ############
#####################################
portfolio-title: Related Sites
portfolio-description: >
  Click the images below to visit the site for each service.

#
# Portfolio Grid
#
portfolio-categories:
  [Lisa, Ray]
portfolio:
  # Portfolio Item - Salon
  - title: <span title="CocoaColorLab.Salon">C<span class="thin">ocoa</span>C<span class="thin">olor</span>L<span class="thin">ab</span>.S<span class="thin">alon</span></span>
    categories: [Lisa]
    image: colorlab-salon-portfolio-image.png
    info: Lisa's hair salon services (this site)
    url: "https://cocoacolorlab.salon"
  # Portfolio Item - Com
  - title: <span title="CocoaColorLab.Art">C<span class="thin">ocoa</span>C<span class="thin">olor</span>L<span class="thin">ab</span>.C<span class="thin">om</span></span>
    categories: [Lisa,Ray]
    image: colorlab-com-portfolio-image.png
    info: Main company website
    url: "https://cocoacolorlab.com"
  # Portfolio Item - Ink
  - title: <span title="CocoaColorLab.Ink">C<span class="thin">ocoa</span>C<span class="thin">olor</span>L<span class="thin">ab</span>.I<span class="thin">nk</span></span>
    categories: [Ray]
    image: colorlab-ink-portfolio-image.png
    info: Ray's tattoo services
    url: "https://cocoacolorlab.ink"
  # Portfolio Item - Art
  - title: <span title="CocoaColorLab.Art">C<span class="thin">ocoa</span>C<span class="thin">olor</span>L<span class="thin">ab</span>.A<span class="thin">rt</span></span>
    categories: [Ray]
    image: colorlab-art-portfolio-image.png
    info: Ray's art portfolio
    url: "https://cocoacolorlab.art"

#####################################
#############   Footer   ############
#####################################
footer-description: Cocoa Color Lab Salon is also on social media.
footer-copyright-text: Cocoa Color Lab, LLC
footer-copyright-year: 2023
